"""Add mentor, session, message, and payment tables

Revision ID: 2927c32a42be
Revises: aa773f10e0d2
Create Date: 2025-11-02 13:12:50.218747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2927c32a42be'
down_revision = 'aa773f10e0d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

